### ISSUE TITLE
No way to get size of device or disk

### ISSUE THREAD

**Issue by M0E-lnx** [xzased/reparted#2]
I looked around and found no way to get the size of a device or disk object.

**Comment by xzased** [comment]
True... how didn't I thought of that? Thanks for the observation, I will include this in the next release that should come out early next week.

**Comment by M0E-lnx** [comment]
Thank you.

**Comment by xzased** [comment]
Well, so much for early last week ha, but it is finally done, along with some bugs I found in the way.
