### ISSUE TITLE
importing reparted in python 3 is failing

### ISSUE THREAD

**Issue by pradeep288** [xzased/reparted#5]
from reparted import *
  File "/usr/lib/python3.5/site-packages/reparted/__init__.py", line 16, in <module>
    from .size import Size
  File "/usr/lib/python3.5/site-packages/reparted/size.py", line 16, in <module>
    from exception import SizeError
ImportError: No module named 'exception'

**Comment by pradeep288** [comment]
its workinh

**Comment by prettyokay-software** [comment]
How did you get this working?

**Comment by prettyokay-software** [comment]
Well, the import issues were solved here https://github.com/agumonkey/reparted/commit/3c73c04d6f367a0658e29f2a2cdabb6cd2a5d35f

There's still some other work that would need to be done to get everything working 100%
